'use strict';

// TODO if we were to invert the keys and values we wouldn't need to iterate through these for each event
// module.exports = {
//   '@long-running-customers': new Set(['eeoc.gov', 'goowill.jobs', 'njstatelib.org', 'perkins.org', 'zoomtext.com', 'leadingage.org' ]),
//   '@vision-care': new Set(['lowvisionbc.ca', 'lowvisionofmn.com', 'southernlowvision.com', 'kansaslowvisiondoctor.com', 'lowvisionvermont.com', 'ialvs.com', 'midwestlowvision.com', 'lowvisioncarepa.com', 'lowvisioncare.com', 'virginialowvision.com']),
//   '@toolbar': new Set(['lowvisionbc.ca', 'lowvisionofmn.com', 'southernlowvision.com', 'kansaslowvisiondoctor.com', 'lowvisionvermont.com', 'ialvs.com', 'midwestlowvision.com', 'lowvisioncarepa.com', 'lowvisioncare.com', 'virginialowvision.com', 'bestfriends.org', 'amacusg.org', 'millburnlibrary.org', 'aidb.org', 'asdsilentwarriors.com', 'sharonpubliclibrary.org', 'ridgefieldparkpubliclibrary.org', 'myactivesenior.com']),
//   '@education': new Set(['belmont.k12.ma.us', 'mtsac.edu', 'asdsilentwarriors.com', 'aidb.org', 'fullerton.edu', 'nyise.org']),
//   '@libraries': new Set(['millburnlibrary.org', 'njstatelib.org', 'sharonpubliclibrary.org', 'catalog.ocln.org', 'warrenlib.org', 'maine.gov', 'ridgefieldparkpubliclibrary.org']),
//   '@seniors': new Set(['cornerstonecareoption.com', 'ouragingmarket.com', 'lowvisionfocus.org', 'leadingage.org', 'makingcareeasier.com', 'myactivesenior.com']),
//   '@blind-and-low-vision': new Set(['lowvisionbc.ca', 'atkratter.com', 'acbohio.org', 'lowvisionofmn.com', 'aroga.com', 'chicagolighthouse.org', 'baumusa.com', 'overhereconsulting.net', 'blindenverband.at', 'southernlowvision.com', 'sightandsound.co.uk', 'virtualvisiontech.com', 'kansaslowvisiondoctor.com', 'lowvisionvermont.com', 'gwmicro.com', 'windoweyesforoffice.com', 'ialvs.com', 'nelowvision.com', 'nelowvision.com', 'aidb.org', 'midwestlowvision.com', 'lowvisioncarepa.com', 'lowvisioncare.com', 'virginialowvision.com', 'perkins.org', 'aisquared.com', 'zoomtext.com', 'window-eyes.at', 'duxburysystems.com', 'floridareading.com', 'myblindspot.org', 'mydigitalapex.com']),
//   '@jobs': new Set(['goodwill.jobs', 'disability.jobs', 'jobswithoutlimits.org', 'acs-dahl.com']),
//   '@high-traffic-sites': new Set(['eeoc.gov', 'goodwill.jobs', 'bestfriends.org', 'njstatelib.org', 'catalog.ocln.org', 'mtsac.edu', 'leadingage.org', 'fullerton.edu', 'perkins.org', 'zoomtext.com'])
// };
//
module.exports = {
  'acbohio.org': ['@blind-and-low-vision'],
  'acs-dahl.com': ['@jobs'],
  'aidb.org': ['@toolbar','@education','@blind-and-low-vision'],
  'aisquared.com': ['@blind-and-low-vision'],
  'amacusg.org': ['@toolbar'],
  'aroga.com': ['@blind-and-low-vision'],
  'asdsilentwarriors.com': ['@toolbar','@education'],
  'atkratter.com': ['@blind-and-low-vision'],
  'baumusa.com': ['@blind-and-low-vision'],
  'belmont.k12.ma.us': ['@education'],
  'bestfriends.org': ['@high-traffic-sites'],
  'blindenverband.at': ['@blind-and-low-vision'],
  'catalog.ocln.org': ['@libraries','@high-traffic-sites'],
  'chicagolighthouse.org': ['@blind-and-low-vision'],
  'cornerstonecareoption.com': ['@seniors'],
  'disability.jobs': ['@jobs'],
  'duxburysystems.com': ['@blind-and-low-vision'],
  'eeoc.gov': ['@long-running-customers','@high-traffic-sites'],
  'floridareading.com': ['@blind-and-low-vision'],
  'fullerton.edu': ['@education','@high-traffic-sites'],
  'goodwill.jobs': ['@jobs','@high-traffic-sites'],
  'goowill.jobs': ['@long-running-customers'],
  'gwmicro.com': ['@blind-and-low-vision'],
  'ialvs.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'jobswithoutlimits.org': ['@jobs'],
  'kansaslowvisiondoctor.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'leadingage.org': ['@long-running-customers','@seniors','@high-traffic-sites'],
  'lowvisionbc.ca': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'lowvisioncare.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'lowvisioncarepa.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'lowvisionfocus.org': ['@seniors'],
  'lowvisionofmn.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'lowvisionvermont.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'maine.gov': ['@libraries'],
  'makingcareeasier.com': ['@seniors'],
  'midwestlowvision.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'millburnlibrary.org': ['@toolbar','@libraries'],
  'mtsac.edu': ['@education','@high-traffic-sites'],
  'myactivesenior.com': ['@toolbar','@seniors'],
  'myblindspot.org': ['@blind-and-low-vision'],
  'mydigitalapex.com': ['@blind-and-low-vision'],
  'nelowvision.com': ['@blind-and-low-vision'],
  'njstatelib.org': ['@long-running-customers','@libraries','@high-traffic-sites'],
  'nyise.org': ['@education'],
  'ouragingmarket.com': ['@seniors'],
  'overhereconsulting.net': ['@blind-and-low-vision'],
  'perkins.org': ['@long-running-customers','@blind-and-low-vision','@high-traffic-sites'],
  'ridgefieldparkpubliclibrary.org': ['@toolbar','@libraries'],
  'sharonpubliclibrary.org': ['@toolbar','@libraries'],
  'sightandsound.co.uk': ['@blind-and-low-vision'],
  'southernlowvision.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'virginialowvision.com': ['@vision-care','@toolbar','@blind-and-low-vision'],
  'virtualvisiontech.com': ['@blind-and-low-vision'],
  'warrenlib.org': ['@libraries'],
  'window-eyes.at': ['@blind-and-low-vision'],
  'windoweyesforoffice.com': ['@blind-and-low-vision'],
  'zoomtext.com': ['@long-running-customers','@blind-and-low-vision','@high-traffic-sites']
};